# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nucleus < Formula
  desc "Profile-aware MCP gateway — one connector, many accounts"
  homepage "https://github.com/doramirdor/nucleusmcp"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/doramirdor/nucleusmcp/releases/download/v0.1.2/nucleus_0.1.2_darwin_amd64.tar.gz"
      sha256 "7557f801f224d6e41540a5c840cede404fa597e5b111185483d9cb2f934f456c"

      define_method(:install) do
        bin.install "nucleus"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/doramirdor/nucleusmcp/releases/download/v0.1.2/nucleus_0.1.2_darwin_arm64.tar.gz"
      sha256 "6778d1d2b31161338306382b86c7a21453a8b16696e667ee12cbab4d2e57a593"

      define_method(:install) do
        bin.install "nucleus"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/doramirdor/nucleusmcp/releases/download/v0.1.2/nucleus_0.1.2_linux_amd64.tar.gz"
      sha256 "d9a3e652edc1683248963216622e340240ca8d8cd1906d74ff98bd27fac3de16"
      define_method(:install) do
        bin.install "nucleus"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/doramirdor/nucleusmcp/releases/download/v0.1.2/nucleus_0.1.2_linux_arm64.tar.gz"
      sha256 "3cadf6ae8dcf43f4193b8973e71621744c51005e7f62b5f6be1b5ae06537fdd3"
      define_method(:install) do
        bin.install "nucleus"
      end
    end
  end

  test do
    system "#{bin}/nucleus", "--version"
  end
end
