# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nucleus < Formula
  desc "Profile-aware MCP gateway — one connector, many accounts"
  homepage "https://github.com/doramirdor/nucleusmcp"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/doramirdor/nucleusmcp/releases/download/v0.1.3/nucleus_0.1.3_darwin_amd64.tar.gz"
      sha256 "0708b3d73a2b9db03ff59a7dae2934249ace40f358fa3e867a3425df0f7b5cb9"

      define_method(:install) do
        bin.install "nucleus"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/doramirdor/nucleusmcp/releases/download/v0.1.3/nucleus_0.1.3_darwin_arm64.tar.gz"
      sha256 "a221ca3cdc397ceebfa5f955ff2350dbd07c612db2b11ae31906fbcb176d0cec"

      define_method(:install) do
        bin.install "nucleus"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/doramirdor/nucleusmcp/releases/download/v0.1.3/nucleus_0.1.3_linux_amd64.tar.gz"
      sha256 "cb9c4df2a8f010d840836df61be94d09c9f72bbd9d77e52018e4caab205bb950"
      define_method(:install) do
        bin.install "nucleus"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/doramirdor/nucleusmcp/releases/download/v0.1.3/nucleus_0.1.3_linux_arm64.tar.gz"
      sha256 "0da4269d5a096d2145a12f4acfe0c131b1c35e546e3b76d8ecd728872ca12f2d"
      define_method(:install) do
        bin.install "nucleus"
      end
    end
  end

  test do
    system "#{bin}/nucleus", "--version"
  end
end
