# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nucleus < Formula
  desc "Profile-aware MCP gateway — one connector, many accounts"
  homepage "https://github.com/doramirdor/nucleusmcp"
  version "0.1.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/doramirdor/nucleusmcp/releases/download/v0.1.4/nucleus_0.1.4_darwin_amd64.tar.gz"
      sha256 "a3ed758117104b9dbbd99ca9154957c68790550cdcf42830ff36e069aad4d92f"

      define_method(:install) do
        bin.install "nucleus"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/doramirdor/nucleusmcp/releases/download/v0.1.4/nucleus_0.1.4_darwin_arm64.tar.gz"
      sha256 "6c2d54e39354caf3a33328b9028e3d96b14eb3b4e1d36927b31b08882029db93"

      define_method(:install) do
        bin.install "nucleus"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/doramirdor/nucleusmcp/releases/download/v0.1.4/nucleus_0.1.4_linux_amd64.tar.gz"
      sha256 "0de4146ec324da62ccce6bb4667993cd6fe5aaf5d71fee8649e57e96b8bf9ace"
      define_method(:install) do
        bin.install "nucleus"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/doramirdor/nucleusmcp/releases/download/v0.1.4/nucleus_0.1.4_linux_arm64.tar.gz"
      sha256 "9c3af7ce62acc97d5bc270c06facca4c9b38b895ad784401655f68d8a9d39ac4"
      define_method(:install) do
        bin.install "nucleus"
      end
    end
  end

  test do
    system "#{bin}/nucleus", "--version"
  end
end
